#!/bin/bash

echo -e "\n[CHECKING THE PRESENCE OF AN EXISTING experiments/ DIRECTORY.]....\n"

if [ -d "experiments/" ]; then
    echo -e "[experiments/ DIRECTORY FOUND. NUKED.]....\n"
    rm -rf experiments/
else
    echo -e "[NO experiments/ DIRECTORY FOUND. CONTINUING NORMALLY.]....\n"
fi
sleep 1

echo -e "[CLONING THE CODE DIRECTORY].....\n"
git clone --no-checkout --depth 1 https://github.com/aggrawal-ankur/glibc-malloc-expedition experiments/
sleep 1

echo -e "\n[CHANGE DIRECTORY TO experiments/]....\n"
cd experiments/ || exit
sleep 1

echo -e "[SETTING UP THE EXPERIMENTS]....\n"
git sparse-checkout init --no-cone
git sparse-checkout set "/dynamic-analysis/*"
git checkout
sleep 1

echo -e "[CLEANUP]....\n"
mv ./dynamic-analysis/* .
rm -rf dynamic-analysis/
echo -e "....[CLEANUP DONE; SETUP DONE]\n"
sleep 1

echo -e "[EXPERIMENTS DIRECTORY PREPARED WITH THE CODE]....\n"

chmod u+x chunk/build
chmod u+x bins/build
rm /experiments/setup

echo -e "[CHANGE DIRECTORY TO experiments/]....\n"
echo -e "[CHOOSE YOUR EXPERIMENTS DIRECTORY AND CD INTO IT]....\n"
echo -e "[OPEN AN EXPERIMENT IN VIM AND READ THE CODE AND THE WALKTHROUGH]....\n"
echo -e "[USE THE BUILD SCRIPT TO BUILD AND EXECUTE AN EXPERIMENT.]....\n"
